name: Build Resume and Preview

on:
  push:
    branches:
      - main
    paths:
      - '**.tex'

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          # Updated to match the new filename (No spaces!)
          root_file: Umar_Akram_iOS_Dev.tex

      - name: Install Poppler
        run: sudo apt-get install -y poppler-utils

      - name: Generate Preview Image
        # Converts the new PDF to resume-preview.png
        run: pdftoppm -png -f 1 -l 1 -singlefile Umar_Akram_iOS_Dev.pdf resume-preview

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-compile Resume and Preview [skip ci]"
          # Commits the new PDF and the Preview image
          file_pattern: "Umar_Akram_iOS_Dev.pdf resume-preview.png"